spring:
  application:
    name: migration
  datasource:
    url: jdbc:sqlite:my_database.db
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/changelog-for-sqlte.yaml
